Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices
<Assembly: AssemblyTitle("CA-Measure")>
<Assembly: AssemblyDescription("")>
<Assembly: AssemblyCompany("")>
<Assembly: AssemblyProduct("CA-Measure")>
<Assembly: AssemblyCopyright("")>
<Assembly: AssemblyTrademark("")> 
<Assembly: ComVisible(False)>
<Assembly: Guid("d1a0810e-8f74-4b8c-953b-0c07b511ab82")> 
<Assembly: AssemblyVersion("1.0.0.0")> 
<Assembly: AssemblyFileVersion("1.0.0.0")> 
